Fix gcc-10 version
Currently specified gcc-10 version '10.2.0-5ubuntu1~20.04' is no longer
avaiable as evident from louhi build failure.
https://louhi.dev/?branch=release-1.9.0-gke&projectId=5192261319262208#/execution-detail/5749343867109376

Error: E: Version '10.2.0-5ubuntu1~20.04' for 'gcc-10' was not found

Hence, removing the specific version and allowing to pull the latest
available version of gcc-10.

BUG: b/191649002
Change-Id: Ie3375073fd9012198746f4fa6ce64c6d4c7dc4c4