fix: strip dsr ip option
Before forwarding the traffic to the endpoint
1. strip the DSR IP option
2. recalculate the checksum

Change to XDP helper is necessary, as `tail_lb_ipv4` call heirarchy cannot include calls to `abort`:

> error: include/bpf/ctx/xdp.h:329:4: in function tail_lb_ipv4 i32 (%struct.xdp_md*): A call to built-in function 'abort' is not supported.
>
> make[1]: *** [Makefile:40: xdp_nodeport_lb4_dsr_lb.o] Error 1

Update tests for backend to not check for IP option.
This is implicitly checked by accessing the expected location of the L4
header information.

Carry-Patch-Approval: b/316609943
Bug: b/308206072
Change-Id: I8d74d5bf56f34617a53433d7b46c1c0a10af4dd8
Reviewed-on: https://gke-internal-review.googlesource.com/c/third_party/cilium/+/895387
Reviewed-by: Prow_Bot_V2 <425329972751-compute@developer.gserviceaccount.com>
Reviewed-by: Akhil Velagapudi <avelagap@google.com>
Unit-Verified: Prow_Bot_V2 <425329972751-compute@developer.gserviceaccount.com>
Tested-by: Prow_Bot_V2 <425329972751-compute@developer.gserviceaccount.com>